# Static Site Hosting on AWS
#
# Copyright © 2019 - 2020, Brendon Matheson
#
# http://brendonmatheson.com/
#
# This is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License v2 as published by the Free Software
# Foundation.
#
# This is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this code.  If not, see http://www.gnu.org/licenses/gpl-2.0.html
---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates the AWS S3 buckets for hosting a static site on a 'naked' domain with inbound redirection from a 'www' domain and access logging"

Parameters: 
  LogBucketName: 
    Type: String
    Default: "log-bucket-name"
    Description: "The name of the logs bucket created with the stack in 01-log-bucket.yaml"
  NakedDomainName: 
    Type: String
    Default: "yourdomain.com"
    Description: "The naked domain name which will be used as the main site bucket"
  RedirectorProtocol:
    Type: String
    Default: "http"
    Description: "If you are using S3 hosting only, then this should be http.  If you are also setting up CloudFront with the stack 03-cloud-front.yaml then this should be https"

Resources:

  #
  # Site Bucket
  #

  SiteBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref "NakedDomainName"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      LoggingConfiguration:
        DestinationBucketName: !Ref "LogBucketName"
        LogFilePrefix: !Sub "${NakedDomainName}/"

  SiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref "SiteBucket"
      PolicyDocument:
        Statement:
        - Sid: "Permit public read access to the site bucket"
          Principal:
            AWS: "*"
          Action:
          - "s3:GetObject"
          Effect: "Allow"
          Resource: !Sub "arn:aws:s3:::${NakedDomainName}/*"
        - Sid: "Permit buildsystem to write to the site bucket"
          Principal:
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/buildsystem"
          Action:
          - "s3:*"
          Effect: "Allow"
          Resource:
          - !Sub "arn:aws:s3:::${NakedDomainName}/*"

  #
  # Redirector Buckets
  #

  RedirectorBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "www.${NakedDomainName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref "NakedDomainName"
          Protocol: !Ref "RedirectorProtocol"
