# Static Site Hosting on AWS
#
# Copyright © 2019 - 2020, Brendon Matheson
#
# http://brendonmatheson.com/
#
# This is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License v2 as published by the Free Software
# Foundation.
#
# This is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this code.  If not, see http://www.gnu.org/licenses/gpl-2.0.html
---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates the AWS S3 buckets for hosting a static site on a 'naked' domain with inbound redirection from a 'www' domain and access logging"

Parameters: 
  NakedDomainName: 
    Type: String
    Default: "yourdomain.com"
    Description: "The naked domain name which will be used as the main site bucket"

Resources:

  #
  # Site Bucket
  #

  SiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Fn::ImportValue: !Sub
          - "${DashedNakedDomainName}-site-bucket-id"
          - DashedNakedDomainName:
              Fn::Join:
                - "-"
                - Fn::Split: [ ".", !Ref "NakedDomainName" ]
      PolicyDocument:
        Statement:
        # - Sid: "Permit public read access to the site bucket"
        #   Principal:
        #     AWS: "*"
        #   Action:
        #   - "s3:GetObject"
        #   Effect: "Allow"
        #   Resource: !Sub "arn:aws:s3:::${NakedDomainName}/*"
        - Sid: "BuildSystemWriteSiteBucket"
          Principal:
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/buildsystem"
          Action:
          - "s3:*"
          Effect: "Allow"
          Resource:
          - !Sub "arn:aws:s3:::${NakedDomainName}"
          - !Sub "arn:aws:s3:::${NakedDomainName}/*"
        - Sid: "CloudFrontReadSiteBucket"
          Principal:
            AWS:
              Fn::ImportValue: !Sub
                - "${DashedNakedDomainName}-oai-principal"
                - DashedNakedDomainName:
                    Fn::Join:
                      - "-"
                      - Fn::Split: [ ".", !Ref "NakedDomainName" ]
          Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource:
          - !Sub "arn:aws:s3:::${NakedDomainName}/*"
