# Static Site Hosting on AWS
#
# Copyright © 2019 - 2022, Brendon Matheson
#
# http://brendonmatheson.com/
#
# This is free software: you can redistribute it and/or modify it under the terms
# of the GNU General Public License v2 as published by the Free Software
# Foundation.
#
# This is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this code.  If not, see http://www.gnu.org/licenses/gpl-2.0.html
---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates a static website stored in AWS S3 and using CloudFront with a 'naked' domain with inbound redirection from a 'www' domain and access logging"

Parameters:
  HostedZoneId:
    Type: "String"
    Default: "TODO"
    Description: "The ID of the hosted zone for this site's domain name"
  NakedDomainName: 
    Type: String
    Default: "yourdomain.com"
    Description: "The naked domain name which will be used as the main site bucket"

Resources:

  #
  # Site Bucket
  #

  SiteBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref "NakedDomainName"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      LoggingConfiguration:
        DestinationBucketName: !ImportValue "log-bucket-name"
        LogFilePrefix: !Sub "${NakedDomainName}/"

  #
  # Certificates
  #

  NakedCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Ref "NakedDomainName"
      ValidationMethod: "DNS"
      SubjectAlternativeNames:
        - !Sub "www.${NakedDomainName}"

  #
  # CloudFront
  #

  OAI:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties: 
      CloudFrontOriginAccessIdentityConfig: 
        Comment: !Sub "OAI-${NakedDomainName}"

  NakedDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref "NakedDomainName"
          - !Sub "www.${NakedDomainName}"
        CustomErrorResponses:
          - ErrorCachingMinTTL: 10
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /errors/404.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: True
          TargetOriginId: !Sub "S3-${NakedDomainName}"
          ViewerProtocolPolicy: "redirect-to-https"
          FunctionAssociations:
            - EventType: "viewer-request"
              FunctionARN: !ImportValue "default-document-function-arn"
        DefaultRootObject: "index.html"
        Enabled: True
        Origins:
          - DomainName: !Sub "${NakedDomainName}.s3.amazonaws.com"
            Id: !Sub "S3-${NakedDomainName}"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OAI}"
        PriceClass: "PriceClass_100"
        ViewerCertificate:
          AcmCertificateArn: !Ref "NakedCertificate"
          MinimumProtocolVersion: "TLSv1"
          SslSupportMethod: "sni-only"

  NakedRecord:
    Type: "AWS::Route53::RecordSet"
    Properties: 
      AliasTarget:
        DNSName: !GetAtt "NakedDistribution.DomainName"
        HostedZoneId: "Z2FDTNDATAQYW2"
      HostedZoneId: !Ref "HostedZoneId"
      Name: !Ref "NakedDomainName"
      Type: "A"

  #
  # Site Bucket Policy
  #

  SiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref "SiteBucket"
      PolicyDocument:
        Statement:
        - Sid: "BuildSystemWriteSiteBucket"
          Principal:
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/buildsystem"
          Action:
          - "s3:*"
          Effect: "Allow"
          Resource:
          - !Sub "arn:aws:s3:::${NakedDomainName}"
          - !Sub "arn:aws:s3:::${NakedDomainName}/*"
        - Sid: "CloudFrontReadSiteBucket"
          Principal:
            AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OAI}"
          Effect: "Allow"
          Action:
            - "s3:*"
            - "s3:ListBucket"
          Resource:
          - !Sub "arn:aws:s3:::${NakedDomainName}"
          - !Sub "arn:aws:s3:::${NakedDomainName}/*"
